import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Characters from "../components/Characters";
import { useState } from "react";
import { ApolloClient } from "@apollo/client/core";
import { InMemoryCache } from "@apollo/client/core";
import { gql } from "@apollo/client/core";
import {
  Heading,
  Box,
  Flex,
  Input,
  Stack,
  IconButton,
  useToast,
} from "@chakra-ui/react";
import { SearchIcon, CloseIcon } from "@chakra-ui/icons";

export default function Home(results) {
  const initialState = results;
  const [characters, setCharacters] = useState(initialState.characters);
  const [search, setSearch] = useState("");
  const toast = useToast();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" justify="center" align="center">
        <Box
          mb={4}
          flexDirection="column"
          align="center"
          justify="center"
          py={8}
        >
          <Heading as="h1" size="2xl" mb={8}>
            Rick and Morty
          </Heading>
          <form
            onSubmit={async (event) => {
              event.preventDefault();
              const results = await fetch("/api/SearchCharacters", {
                method: "post",
                body: search,
              });
              const { characters, error } = await results.json();
              if (error) {
                toast({
                  position: "bottom",
                  title: "An error has occured",
                  description: error,
                  status: "error",
                  duration: 5000,
                  isClosable: true,
                });
              } else {
                setCharacters(characters);
              }
            }}
          >
            <Stack maxWidth="350px" width="100%" isInline mb={8}>
              <Input
                placeHolder="Search"
                value={search}
                border="none"
                onChange={(e) => setSearch(e.target.value)}
              />
              <IconButton
                colorScheme="blue"
                aria-label="Search database"
                icon={<SearchIcon />}
                disabled={search === ""}
                type="submit"
              />
              <IconButton
                colorScheme="red"
                aria-label="Reset button"
                icon={<CloseIcon />}
                disabled={search === ""}
                onClick={async () => {
                  setSearch("");
                  setCharacters(initialState.characters);
                }}
              />
            </Stack>
          </form>
          <Characters characters={characters} />
        </Box>
      </Flex>
    </>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://rickandmortyapi.com/graphql/",
    cache: new InMemoryCache(),
  });
  const { data } = await client.query({
    query: gql`
      query {
        characters(page: 1) {
          info {
            count
            pages
          }
          results {
            id
            name
            location {
              id
              name
            }
            origin {
              id
              name
            }
            episode {
              id
              episode
            }
            image
          }
        }
      }
    `,
  });

  return {
    props: {
      characters: data.characters.results,
    },
  };
}
